### ISSUE TITLE
eunit generator tries to recreate existing test_()

### ISSUE THREAD

**Issue by tuncer** [triqng/triq#17]
eunit fails because `test/lock_fsm.erl:lock_fsm_test_()` already exists.

Shouldn't eunit support avoid this by either generating a module-unique name, or alternatively provide the ability to ignore a module via, say, `-no_triq_eunit(true)` or `-compile(no_triq_eunit)`?

**Comment by zkessin** [comment]
I think would be even better to say you have to opt in with `-compile(triq_eunit).` or the like

**Comment by tuncer** [comment]
Submitted patch (#20), closing.
