### ISSUE TITLE
Add docs for hex package

### ISSUE THREAD

**Issue by aerosol** [triqng/triq#29]

**Comment by tuncer** [comment]
What exactly has to be done here?

**Comment by aerosol** [comment]
Review current docs, generate & publish edoc, as seen in http://www.rebar3.org/docs/publishing-packages

**Comment by tuncer** [comment]
I can't think of much that needs to be added besides the `-triq(eunit)` feature. Maybe let's publish the docs as they are, unless you think they're in bad shape, and re-publish after we've revised it. We could change this ticket to track documentation TODO items instead.

**Comment by aerosol** [comment]
@tuncer agreed 👍

**Comment by tuncer** [comment]
See https://github.com/triqng/triq/pull/40

**Comment by tuncer** [comment]
See #42

**Comment by tuncer** [comment]
With #42 merged, I think this can be closed as resolved.

**Comment by tuncer** [comment]
Closing, fixed by #40 and #42.
