### ISSUE TITLE
Update README with hex installation instructions

### ISSUE THREAD

**Issue by aerosol** [triqng/triq#30]

**Comment by tuncer** [comment]
What exactly has to be done here? Blocked by #29?

**Comment by aerosol** [comment]
No, not blocked. I meant some basic information how to fetch the dependency from hex. This implies rebar3 usage.

**Comment by tuncer** [comment]
Do you mean different ways (e.g. versions) of specifying the dependency in, say, rebar.config?

**Comment by aerosol** [comment]
@tuncer I meant the latter, so it's clear how to use the package itself (and the fact it _can_ be used).

**Comment by tuncer** [comment]
Done: #42

**Comment by tuncer** [comment]
With #42 merged, I think this can be closed as resolved.

**Comment by tuncer** [comment]
Closing, fixed by #42.
