### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by aerosol** [triqng/triq#31]
@tuncer prefers GitLab CI. I'm wondering if we could integrate with GitHub PRs.

**Comment by tuncer** [comment]
Maybe? https://docs.gitlab.com/ee/ci/triggers/#triggering-a-pipeline-from-a-webhook

**Comment by tuncer** [comment]
While the GitLab-CI API call URL is clear, my digging in https://developer.github.com/v3/orgs/hooks/ and https://developer.github.com/v3/activity/events/ was inconclusive:

1. didn't find how to substitute the git ref in the URL with that of the GitHub event's
2. the trigger would probably not work since we would ask GitLab-CI to CI something it may not yet have mirrored

@aerosol, @zkessin, if one of you has experience with any one of https://github.com/marketplace/category/continuous-integration, how about we set that up for the github repo and keep using GitLab-CI over there? Maybe a combination of AppVeyor with one of CircleCI or Travis-CI?

**Comment by KrzysiekJ** [comment]
Or maybe make GitLab repository a canonical one?

**Comment by tuncer** [comment]
I like GitLab, but I don't know if it's wise to declare it canonical after the project has existed here (first) for years. I'm also in favor of having both for higher availability. That said, mirroring is uni-directional right now (github -> gitlab), but we could make it bi-directional if we wanted to. @KrzysiekJ, unless you disagree, let's configure CI here as well.

**Comment by tuncer** [comment]
Implemented the needed Travis-CI changes: https://github.com/triqng/triq/pull/41

**Comment by tuncer** [comment]
I created and invited the user `triqci` into a new team named `CI`, but I cannot find the permissions settings to limit the user to only commenting, which I think is all that Travis-CI needs. Any idea?

**Comment by tuncer** [comment]
@zkessin, which account should own Travis-CI jobs?

**Comment by tuncer** [comment]
> Or maybe make GitLab repository a canonical one?

While I was migrating the old GitHub Pages HTML to GitLab pages and making preparations for the initial public release, I started to consider this a good idea which, if we do it, has to happen prior to the first release.

**Comment by tuncer** [comment]
> Or maybe make GitLab repository a canonical one?

While I was migrating the old GitHub Pages site to GitLab Pages and making preparations for the initial public release, I started to consider this a good idea which, if we do it, has to happen before the public announcement. It's still impossible to disable pull requests in GitHub projects AFAICS, so maybe we should to clear the GitHub org to avoid _"please submit patches over at gitlab"_ responses and general project location confusion. Triq releases are on Hex, so the location won't matter to those who just use it as a dependency.

**Comment by tuncer** [comment]
> Or maybe make GitLab repository a canonical one?

While I was migrating the old GitHub Pages site to GitLab Pages and making preparations for the initial public release, I started to consider this a good idea which, if we do it, has to happen before the public announcement. Because it's still impossible to disable pull requests in GitHub projects AFAICS, maybe we should clear the GitHub org to avoid _"please submit patches over at gitlab"_ responses and general project location confusion. Also, Triq releases are on Hex, so the location won't matter to those who just use it as a dependency.

**Comment by tuncer** [comment]
See #56 for finished and improved pages implementation which uses GitLab Pages. Let's merge that and ideally also swap primary/mirror roles (as discussed here) before we publicly announce the first release. It would be a lot cleaner and less confusing that way.

**Comment by KrzysiekJ** [comment]
I vote for GitLab. Perhaps GitHub should be kept as a mirror at least for some time, as https://github.com/triqng/triq returning 404 may make the new location more difficult to find in some cases and it will break builds in projects which directly link current Git repository. Also deleting the triqng organization will not make the original repository by @krestenkrab disappear. And we don’t currently get many external pull requests, so handling cases in which they are submitted on GitHub should not be much burden.

Refs dear-github/dear-github#84.

**Comment by KrzysiekJ** [comment]
Since @tuncer has secured the https://gitlab.com/triq organization, how about using that one instead of https://gitlab.com/triqng when we move to GitLab?

**Comment by KrzysiekJ** [comment]
Thoughts? @aerosol @hlieberman @MirkoBonadei @zkessin

**Comment by tuncer** [comment]
FYI, GitLab pages already works and README.org plus a section for linking the generated EDoc is automatically published under https://triq.gitlab.io and https://triqng.gitlab.io.

**Comment by tuncer** [comment]
When we move to GitLab, I agree that https://gitlab.com/triq is the right choice. We should ditch the triqng org on GitLab, when the move happens.

**Comment by tuncer** [comment]
> Refs dear-github/dear-github#84.

I hope GitHub one day allows disabling pull request, but despite many parts of the FOSS community requesting, there are no signs (so far) that this will happen. A prominent "this is a read-only mirror, go to gitlab/triq" in the project description header should be enough.

It's imaginable that someone will build a webhook for automatically responding to pull requests in read-only github repos with a "please go here..." and auto close of the PR.

**Comment by tuncer** [comment]
Ping @aerosol @hlieberman @MirkoBonadei @zkessin?

**Comment by hlieberman** [comment]
I agree with the move to Gitlab.  👍, let's ship it.

**Comment by tuncer** [comment]
Steps to migrate:

1. Copy open tickets to gitlab
2. Create prefixed tags (e.g. 1.2.3 -> v1.2.3) to allow maintenance branches (branch 1.2 etc.) and easy filtering
3. Delete old tags
4. Close github tickets
5. Create fresh gitlab project (no mirroring) under https://gitlab.com/triq
6. Adjust GitLab Pages mirror repo to pull from new triq repo
7. Delete https://gitlab.com/triqng org
8. Turn this repo into a read-only mirror of https://gitlab.com/triq/triq
9. Disable tickets and everything we can in this github repo
10. Change project description to point at gitlab project
11. Perhaps add a notice where active project is as first line of CONTRIBUTING.org

Did I forget anything?

**Comment by KrzysiekJ** [comment]
⒓ Update links in `src/triq.app.src`.
