### ISSUE TITLE
Reporting module prints to stdout when shrinking

### ISSUE THREAD

**Issue by KrzysiekJ** [triqng/triq#33]
When shrinking, Triq now prints to stdout information about every tried value (whether it passes or fails). It looks like this:

```
Testing […]
Failed!

Failed after 1 tests with false
xxxFailed!
Failed!
[…]
.x.x..Failed!
.Failed!
x.xxxxxFailed!
x..xxxxxx.xFailed!
x..xFailed!
Failed!
xx.xFailed!
xxx.xxxx.Failed!
xxxFailed!
xx.x.xx.x.x.xxxFailed!
Failed!
Failed!
xFailed!
xxFailed!
.xxxxxxxx.xFailed!
...Failed!
Failed!
Failed!
xFailed!
xxxxFailed!
xSimplified:
```

I guess this change was introduced in commit 2262a902e93ec by @aerosol.

**Comment by tuncer** [comment]
@aerosol, can you take a look?

**Comment by aerosol** [comment]
Hey, sorry, I replied to that one via e-mail but looks like it didn't work.

Strange the problem did not appear when running tests.

I am AFK this month, I'll have a look as soon as possible. Please bare with me. 🍰

**Comment by aerosol** [comment]
@KrzysiekJ hey, can you help me reproduce? I don't have any erlang code at hand, and running eunit via rebar/rebar3 doesn't really manifest this. IIRC eunit captures the stdout, perhaps there's a way to disable it.

**Comment by KrzysiekJ** [comment]
You can either use the Triq plugin for erlang.mk or run Triq directly from Erlang shell, like this:

```erlang
triq:check(Module).
```

**Comment by aerosol** [comment]
Hm, I wonder if this is due to removal of the default "silent" reporter.

**Comment by tuncer** [comment]
Is the "silent" obsolete and not needed/used anymore?
