### ISSUE TITLE
Remove FSM support?

### ISSUE THREAD

**Issue by tuncer** [triqng/triq#34]
`gen_fsm` has been deprecated. Should we do the same for FSM support in Triq?

**Comment by zkessin** [comment]
only if someone wants to build the new state machine code. Until then I think leaving it as it makes sense.

**Comment by tuncer** [comment]
I'm glad you think that way because my first thought was to keep it supported as long as it doesn't cause issues or otherwise imposes maintenance headache.

**Comment by tuncer** [comment]
Filed `gen_statem` ticket (#37), closing.

**Comment by aerosol** [comment]
> gen_fsm has been deprecated

Oh boy, I've been living under the rock lately, @tuncer could you provide some links with regards to that?

**Comment by tuncer** [comment]
Project | Date | Commit
------------ | ------------- |  -------------
Erlang | 2017-04-06 | https://github.com/erlang/otp/commit/c6bdd67b33b70d862e2a2d0f582106f2e930d970
Elixir | 2014-03-08 | https://github.com/elixir-lang/elixir/commit/455eb4c4ace81ce60b347558f9419fe3c33d8bf7
